server:
  port: 7003
spring:
  application:
    name: cloud-eureka-server
eureka:
  instance:
    hostname: eureka3.com #eureka服务端实例名称
  client:
    register-with-eureka: true #false表示不向注册中心注册自己。
    fetch-registry: true #false表示自己就是注册中心，不需要检索服务
    service-url:
      defaultZone: http://eureka2.com:7002/eureka,http://eureka1.com:7001/eureka
